name: Security CI Jobs
on: 
  push:
    branches: [develop]
jobs:
  sensitive-info-scan:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: Secret Scan (Trufflehog)
    steps:

    - name: Checkout the code
      uses: actions/checkout@v4
    
    - name: Install Trufflehog using the script 
      run: curl -sSfL https://raw.githubusercontent.com/trufflesecurity/trufflehog/main/scripts/install.sh | sh -s -- -b /usr/local/bin

    - name: Current working directory
      run: |
        pwd=$(pwd)
        echo "First output: $pwd"
        echo "result=$pwd" >> $GITHUB_ENV

    - name: Extract repo name
      run: |
        echo "Second output: ${{ env.result }}"
        output1=${{ env.result }}
        echo "Third output: $output1"
        output2=${output1##*/}
        echo "Fourth output: $output2"
        echo "output3=$output2" >> $GITHUB_ENV

    - name: Scan the local repo using Trufflehog
      run: trufflehog git file://${{ env.result }} --json > ${{ env.output3 }}-Trufflehog-report.json

    - name: Upload json result file if present
      uses: actions/upload-artifact@v4
      with:
        name: sensitive-info-scan
        path: |
          ${{ env.output3 }}-Trufflehog-report.json
    
  sast-scan:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: SAST (DevSkim and Semgrep)
    steps:
    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install dotnet and DevSkim
      run: |
        wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
        chmod +x ./dotnet-install.sh
        ./dotnet-install.sh
        pwd=$(pwd)
        echo "PWD: $pwd"
        ls -ltr
        dotnet --version
        dotnet tool install --global Microsoft.CST.DevSkim.CLI
        rm -f dotnet-install.sh
        ls -ltr

    - name: Current working directory
      run: |
        ls -ltr
        pwd=$(pwd)
        echo "First output: $pwd"
        echo "result=$pwd" >> $GITHUB_ENV

    - name: Extract repo name
      run: |
        echo "Second output: ${{ env.result }}"
        output1=${{ env.result }}
        echo "Third output: $output1"
        output2=${output1##*/}
        echo "Fourth output: $output2"
        echo "output3=$output2" >> $GITHUB_ENV

    - name: Run SAST scan using DevSkim
      run: |
        echo "Current directory: ${{ env.result }}"
        devskim analyze -I ${{ env.result }} -f sarif --output-format json > ${{ env.output3 }}-DevSkim-report.json

    - name: Upload DevSkim json result file if present
      uses: actions/upload-artifact@v4
      with:
        name: sast-scan-devskim
        path: |
          ${{ env.output3 }}-DevSkim-report.json

    - name: Install Semgrep using Python's Pip
      run: |
        pwd
        ls -ltr
        py_ver=$(python3 --version)
        echo "Python version: $py_ver"
        python3 -m pip install semgrep
        sg_ver=$(semgrep --version)
        echo "Semgrep version: $sg_ver"
        ls -ltr

    - name: Scan the code in current directory and output the results in JSON format using Semgrep
      run: |
        pwd
        ls -ltr
        cd ${{ env.result }}
        semgrep scan --sarif --json-output=${{ env.output3 }}-semgrep-findings.json
        cp ${{ env.output3 }}-semgrep-findings.json ../
        ls -ltr
        ls -ltr ../ 

    #- name: Upload Semgrep sarif report to github code scanning
    #  uses: github/codeql-action/upload-sarif@v3
    #  with:
    #    sarif_file: ${{ env.output3 }}-semgrep-findings.sarif
    #
    - name: Upload Semgrep json result fie if present
      uses: actions/upload-artifact@v4
      with:
        name: sast-scan-semgrep
        path: |
          ${{ env.output3 }}-semgrep-findings.json

  sbom-scan:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: SBOM (Syft)
    steps:
      
    - name: Checkout the code
      uses: actions/checkout@v4
    
    - name: Install Syft
      run: |
        curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

    - name: Current working directory
      run: |
        ls -ltr
        pwd=$(pwd)
        echo "First output: $pwd"
        echo "result=$pwd" >> $GITHUB_ENV

    - name: Extract repo name
      run: |
        echo "Second output: ${{ env.result }}"
        output1=${{ env.result }}
        echo "Third output: $output1"
        output2=${output1##*/}
        echo "Fourth output: $output2"
        echo "output3=$output2" >> $GITHUB_ENV

    - name: Run SBOM scan on the local repo
      run: |
        echo "Current directory: ${{ env.result }}"
        syft ${{ env.result }} --output cyclonedx-json=${{ env.result }}/${{ env.output3 }}-Syft-sbom-report

    - name: Upload json result file if present
      uses: actions/upload-artifact@v4
      with:
        name: sbom-scan
        path: |
          ${{ env.output3 }}-Syft-sbom-report

  sca-scan:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: sbom-scan 
    name: SCA (Grype)
    steps:
    
    - name: Checkout the code
      uses: actions/checkout@v4
      
    - name: Install Grype
      run: |
        curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin
        
    - name: Current working directory
      run: |
        ls -ltr
        pwd=$(pwd)
        echo "First output: $pwd"
        echo "result=$pwd" >> $GITHUB_ENV

    - name: Extract repo name
      run: |
        echo "Second output: ${{ env.result }}"
        output1=${{ env.result }}
        echo "Third output: $output1"
        output2=${output1##*/}
        echo "Fourth output: $output2"
        echo "output3=$output2" >> $GITHUB_ENV

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: sbom-scan

    - name: Run SCA scan on the local repo
      run: |
        echo "Current directory: ${{ env.result }}"
        grype ${{ env.result }}/${{ env.output3 }}-Syft-sbom-report > ${{ env.output3 }}-Grype-sca-report

    - name: Upload Grype scan result file if present
      uses: actions/upload-artifact@v4
      with:
        name: sca-scan-grype
        path: |
          ${{ env.output3 }}-Grype-sca-report
    
